cookie:
  expiry_days: 30
  key: intervuai_cookie
  name: intervuai_auth
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$q5kN8SmjYBcHjF7yxKiA4uRhbFRhQ1/mlV5DkSy67GHayclw55mya
    user:
      email: user@example.com
      name: User
      password: $2b$12$O3r2N/kXTm7joLou4cz3Ye.FfQXqw4..wKdhUBxJAq7/DL0sk.9Ku
preauthorized:
  emails:
  - newuser@example.com
